### ISSUE TITLE
socket return 400 error

### ISSUE THREAD

**Issue by profelis** [SempaiGames/haxe-ga#17]
Hi!

If I turn on useSSL, ThreadedSocketRequest return status 400 here

https://github.com/fbricker/haxe-ga/blob/master/src/googleAnalytics/ThreadedSocketRequest.hx#L34
//  trace(s.input.readLine());

I think you need check this answer and trace this error or/and turn off ssl

**Comment by fbricker** [comment]
Hi, you're right... when added the SocketRequest class (to avoid blocking connections), I've not considered the SSL connections. I'm not sure what's more convenient: Disabling SSL when using SocketRequest, or using UrlLoader when enabling SSL. Thoughts?

**Comment by fbricker** [comment]
Hi, I've uploaded a fixed version of Haxe-ga that re-enables support for SSL on CPP and Neko targets.

Thanks!
