### ISSUE TITLE
Version 0.5.2 fails to install

### ISSUE THREAD

**Issue by JonnyBlackburn** [SempaiGames/haxe-ga#20]
I'm running windows and when i run the command:
``` haxelib install haxe-ga```

I get the error message:
```Unsupported flags 2```

A quick google reveals this is caused by issues when zipping up the project. 
[Link](http://old.haxe.org/forum/thread/555)

**Comment by fbricker** [comment]
Can you tell me wich version of Haxe / Haxelib you have installed?
That sounds like an old bug on some version of haxelib :/

**Comment by JonnyBlackburn** [comment]
Haxe: v3.1.3
Haxeib: v 3.1.0-rc.4

**Comment by fbricker** [comment]
I recommend for you to upgrade to haxe 3.2 if you can do that. This should solve the issue.
Otherwise, you may need to download the library from here: http://lib.haxe.org/p/haxe-ga/
And manually install it.

Please let me know if this fixes your issue.

Thanks!

**Comment by JonnyBlackburn** [comment]
I've downloaded an older version of the library for now.
Thanks for the quick reply.

**Comment by zweimal** [comment]
Lot of people has the same issue, and it isn't due to haxe/haxelib version but zip compression.
I re-zipped it and local-installed it and problem fixed.
Take a look a this old issue: http://old.haxe.org/forum/thread/555
Same problem problem with 'extension-locale'

**Comment by fbricker** [comment]
Can you tell me which version of haxe and haxelib you have installed?
This was an old issue of haxelib (where you needed to use non-compressed zip files, so libraries were bigger). It's strange that you're having this issue with recent haxelib versions.

**Comment by fbricker** [comment]
One thing:
Can you test with this file: https://www.dropbox.com/s/wtyv603nsnn5n1s/haxe-ga.zip?dl=0 (This zip is made using lower compression levels... it may work on your haxelib version).

If it works for your haxelib version, then I can set this by default on this and other extensions.

**Comment by zweimal** [comment]
The point is only 'haxe-ga' and 'extension-locale' have that issue, the rest of the libs works fine.
My Haxe/haxelib versions are same as Jonny.
Package you shared works fine in my computer.
Thanks

**Comment by fbricker** [comment]
Yes... the issue happens on those extensions since the script on those extensions used maximum compression (which does not works on haxelib 3.1.X and lower - but they do work on haxelib 3.2+).

I'll change the package scripts of those extensions so they don't use max. compression to make them work on old haxelib versions.

Thanks!

**Comment by fbricker** [comment]
Done! You can now uninstall haxe-ga and extension-locale and reinstall  them from haxelib. It should work fine.
PS: I didn't change version number, so you'll need to uninstall the current version to allow haxelib to download the new one.

Future versions will still be compatible as the script was modified and committed to github as well.

Thanks again.
